### ISSUE TITLE
Relative transformation and transform.light

### ISSUE THREAD

**Issue by grav** [louisremi/jquery.transform.js#10]
I cannot get relative transformations working with the light-version. With the non-light version it works fine.

If I first do

```
#myDiv{
  transform: "scale(0.3)";
}
```

and then do

``` javascript
var current = $("#myDiv").css("transform");
$("#myDiv").animate({transform: current+"scale(2)"});
```

the div jumps to original size and is then scaled to double size, instead of being scaled from 0.3 to 0.6.

Chrome Dev/Safari 5.1 OS X Lion, JQuery 1.6.2

**Comment by louisremi** [comment]
There is no light version anymore.
