### ISSUE TITLE
not working with jquery animate

### ISSUE THREAD

**Issue by minimit** [louisremi/jquery.transform.js#26]
the old jquery.transform.light.js works good but this new version with transform2d and transform3d doesn't work for me... it works when I assign css with jquery but with animate it only does the first animation not the subsequent changes...

**Comment by louisremi** [comment]
Hi @beaver82,

Could you provide a test case using jsfiddle.net please?

I suspect you might have a problem with relative rotations as well.

**Comment by minimit** [comment]
http://jsfiddle.net/FCU8N/
Now it works nevermind.. but it's not working on ie9.. ie8 works instead

**Comment by louisremi** [comment]
Alright, thanks for your time.
There's an open issue about IE9 problems, don't hesitate to comment on it: https://github.com/louisremi/jquery.transform.js/issues/18 (the problem's that I don't have IE9)

I'm closing this issue.
