### ISSUE TITLE
Animate with delay=0 fails

### ISSUE THREAD

**Issue by Clorr** [louisremi/jquery.transform.js#27]
In this example : http://jsfiddle.net/qGEmy/7/ , animating with delay=0 does fail. Using another value, even null, does work.

**Comment by louisremi** [comment]
You mean duration == 0.
Interesting, I'm on it.

**Comment by louisremi** [comment]
This has been fixed in the commit I just pushed.
Thanks for this bug report @Clorr !

**Comment by Clorr** [comment]
Thanks for your efficiency Mr @louisremi ;-)
