### ISSUE TITLE
Multiple Filters Pt. Deux

### ISSUE THREAD

**Issue by brianblakely** [louisremi/jquery.transform.js#4]
Actually, I totally lied with my previous comment.  I made a mistake while linking from my Dropbox account and did not include the latest version.

Currently-existing filters are still over-written in IE<9: http://jsfiddle.net/22Nac/

**Comment by brianblakely** [comment]
I see that it only works when other filters are in the "style" attribute of the element.  elem.currentStyle['filter'] should be used to analyze the current filter situation, as it combines filters assigned via inline and external CSS into one statement.

**Comment by louisremi** [comment]
Do you really do that? Putting filters in your css?
I'm pretty sure your filter will also break if you set an opacity.

**Comment by brianblakely** [comment]
Yes sir, filter is the best way to do gradient backgrounds in IE, most of the time: http://www.colorzilla.com/gradient-editor/

If jQuery is overwriting all filters to get to opacity (and a quick test says that it might be), that's no good.

**Comment by louisremi** [comment]
Yep,
You're right.

You should file a report on http://bugs.jquery.com
Don't forget to build a jsfiddle showing the problem and if you want to create a pull request, don't forget to do it in a branch: http://docs.jquery.com/Getting_Involved#Committing_and_Pull_Requests
Ask me if you think I can help.

Best regards,

Louis-Rémi

**Comment by brianblakely** [comment]
Yup, filed a ticket earlier today. :)

http://bugs.jquery.com/ticket/8403

I'm considering producing a fork, not sure what the time investment would be.

**Comment by brianblakely** [comment]
Working better than ever, incredible work.

**Comment by louisremi** [comment]
Thanks,

I'm gathering use cases of this plugin, have you got anything public you could share?

Regards,

Louis-Rémi

**Comment by brianblakely** [comment]
I wrote a presentation engine using your plugin.  I'm giving the presentation on the filter property and Raphaël.  It starts in 2.5 hours, you can check it out here if you have the time and volition: https://www2.gotomeeting.com/join/683985954

**Comment by louisremi** [comment]
Too bad, I'll be sleeping at that time (00.30am over here).

**Comment by brianblakely** [comment]
I'm going to polish up the presentation and give it a permanent home online near the end of the month.  Your plugin made building it a breeze, and recent fixes you made (that I was not involved with) repaired some zany IE behavior related to rapid-fire animations. :)

**Comment by louisremi** [comment]
Good!
I'm glad you like the code and I look forward to see what you've build with it.
You're help has been really precious in improving the quality of the plugin.
