### ISSUE TITLE
Offset or Position after a rotation is not correct in firefox

### ISSUE THREAD

**Issue by shragesmilowitz** [louisremi/jquery.transform.js#5]
I you rotate an input box and you then try to get its new position using $(element).position().top or $(element).offset().top it will return the original position vs in IE and Chrome it will give you the new position.

Here is an example: http://jsfiddle.net/shrage/Xv39G/
Click on animate
Then click on "Left position of animate button" and you will see that it returns 18px which is the left position of the buttons original place. in chrome it will give you 400 which is the new position of the button after rotation.

**Comment by louisremi** [comment]
I already noticed that problem.
As you can imagine, the bug is on the browser side, and there's not much I can do about it.
I'll make sure it has been reported.
Regards,
Lr
