### ISSUE TITLE
Looks like a code typo in the plug-in

### ISSUE THREAD

**Issue by aferlazzo** [louisremi/jquery.transform.js#6]
On line 134 in transform.lite.js and line 151 in transform.js there appears to be a non-printable character (shows up as a space) between the '||' and 'elemStyle.filter'. It caused the plug-in to not work until I removed them. You might want to edit the plug-in.

-Anthony

**Comment by louisremi** [comment]
Thank you for reporting this issue. I wonder how long this has been around and why nobody else noticed...
Can you confirm that it is no longer a problem?

**Comment by aferlazzo** [comment]
Louis,

I just downloaded and extracted transform.light.js and it is working the
same as transform.lite.js after I fixed the typo. The original problem was
discovered as I debugged my script using firebug, by the way.

It looks like you _think_ you fixed the IE formatting problem, but I could
not get it to work right with IE 8, the only version I have. the plug-in
seems to forget the setting for LEFT property. I was partially able to
eliminate the problem in my animations by simultaneously rotating a block
and resetting the LEFT property. But in IE the top and left properties have
to be explicitly calculated and stored for each block I want to rotate when
using the IE browser. It certainly would be nice if the transform.js and/or
transform.light.js fully supported IE.

The other thing (not that you asked for feedback) that I noticed lacking was
the ability to set the rotation origin.  Looks like the plug-in only allows
the origin to be (50%,50%) or middle of the block. This works great for
spinning a block like a pin-wheel, but I want to create a sort of
pivot-point hinge effect with my rotation effect.

See my website at http://www.prontocommercial.com. Click on 'Funding' in the
heading on top to see how I used the plug-in to change the heading from
horizontal to vertical. Click on 'Funding' a second time to see how it is
moved back to horizontal orientation. It works best (most smooth) with
Chrome 10.0. The transition from vertical to horizontal is much less smooth
in Firefox 3.6. Well, maybe that's just 3.6. It looks much better in Firefox
4.0.

Anyway, I really like your plug-in. Hopefully you can get the IE problem
worked out. Because IE does its thing with a matrix rather than the way
Mozilla and Webkit do their transitions that may not be an easy task. But
nothing really good is ever easy, is it?

 Best Regards,

Anthony Ferlazzo

http://www.prontocommercial.com/

**Comment by louisremi** [comment]
Hi Anthony, for the translation to work in IE, you have to give you elements a "position: absolute" and wrap them in an element with "position: relative".

Let me know if that solved your problem.

Lr

**Comment by aferlazzo** [comment]
Hi Louis,

In the hopes that I did not originally follow the rule of
'position:absolute' inside 'position:relative' wrapping, I tried once more
to get my wep page application to work with IE8. I double-checked the CSS
file and tried the script to no avail. It does not work correctly.

When I have some time I'll strip out all but the routine in question and
create a 'test case' you can run to see if it is broken on your version of
IE, too.

-Anthony
