### ISSUE TITLE
problem when used with other animations

### ISSUE THREAD

**Issue by minimit** [louisremi/jquery.transform.js#7]
When running it with multiple animations, sometimes it doesn't execute the other animations, in this case the animation top

i've a code like this

var mypath = $("#myid");
mypath.stop().animate({top:0, transform: 'scaleX(2) scaleY(2)'},{queue:true, duration:400, specialEasing: {top:'easeOutExpo', transform:'easeOutExpo'}});

gives same problem with
var mypath = $("#myid");
mypath.stop().animate({transform: 'scaleX(2) scaleY(2)'},{queue:false, duration:400, specialEasing: {transform:'easeOutExpo'}});
mypath.animate({top:0},{queue:false, duration:400, specialEasing: {top:'easeOutExpo'}});

i've also tried another plugin like this, it gives same problem... any thoughts?

**Comment by minimit** [comment]
well i figured it out, giving marginTop instead of top doesn't do problems, maybe it's because it animate to top while it was scaling, so the top value change with scaling?

**Comment by louisremi** [comment]
Thank you for those info, I'll investigate.
